export const NavbarLocator = {
  container: "#navbar",

  menu: {
    pendaftaran: '#navbar a#menu_pendaftaran',
    pelayanan: '#navbar a#menu_pelayanan',
    manajemen: '#navbar a#menu_manajemen',
    backOffice: '#navbar a#menu_pengelolaan:has-text("Back Office")',
    masterData: '#navbar a#menu_pengelolaan:has-text("Master Data")',
    laporan: '#navbar a#menu_laporan',
    grafik: "#navbar a#menu_grafik.dropdown-toggle",
    user: '#navbar a#menu_user',
  },

  pendaftaran: {
    pasien: '#navbar a#menu_pendaftaran_pasien',
    peserta: '#navbar a#menu_pendaftaran_peserta',
    createPasien: '#navbar a#menu_pendaftaran_pendaftaran_v2',
    pendaftaranPasien: '#navbar a#menu_pendaftaran_pendaftaran',
    pendaftaranPasienV2: '#navbar a#menu_pendaftaran_pendaftaran_v2',
    rekamMedis: '#navbar a#menu_pendaftaran_rekammedis',
    antreanKiosk: '#navbar a[onclick*="antreanpendaftaran"]',
    panggilLoketKiosk: '#navbar a#menu_pendaftaran_rekammedis[href*="/loket/index"]',
  },

  pelayanan: {
    medis: '#navbar a#menu_pelayanan_medis',
    rawatJalanIgd: '#navbar a#menu_pemeriksaan_medis[href*="/pemeriksaanmedis"]',
    rawatInap: '#navbar a#menu_pemeriksaan_medis[href*="/rawatinap"]',
    laboratorium: '#navbar a#menu_pelayanan_laboratorium',
    radiologi: '#navbar a#menu_pelayanan_radiologi',
    pemeriksaanAir: '#navbar a#menu_pelayanan_pemeriksaan_air',
    mcu: '#navbar a#menu_pelayanan_mcu',
    rujukanExternal: '#navbar a#menu_pelayanan_rujukan_external',
    pasienMeninggal: '#navbar a#menu_pelayanan_pasienmeninggal',
    obatPasien: '#navbar a#menu_pelayanan_obat_pasien',
    surveyKepuasan: '#navbar a#menu_pelayanan_survey',
    pengelolaanSurveyKepuasan: '#navbar a#menu_pelayanan_survey_pengelolaan',
    surveyKepuasanV2: '#navbar a#menu_pelayanan_survey_v2',
    pengelolaanSurveyKepuasanV2: '#navbar a#menu_pelayanan_survey_pengelolaan_v2',
    programKlinik: '#navbar a#menu_pelayanan_program_puskesmas',
    sinkronisasiKunjunganSehatBpjs: '#navbar a#menu_kunjungansehatbpjs',
    kegiatanKelompok: '#navbar a#menu_kegiatankelompok',
    kontakSehat: '#navbar a#menu_penyuluhankesehatan',
    kasir: '#navbar a#menu_pelayanan_kasir_v2',
    daftarShift: '#navbar a#menu_daftar_shift',
    detailTransaksi: '#navbar a#menu_pelayanan_detail_transaksi',
    resep: '#navbar a#menu_pelayanan_resep',
    resepV2: '#navbar a#menu_pelayanan_resep_v2',
    rujukLanjut: '#navbar a#menu_pelayanan_vclaim_rujuklanjut',
    sep: '#navbar a#menu_SEP',
    rencanaKontrolSpri: '#navbar a#menu_SPRI',
    approvalSep: '#navbar a#menu_approval',
  },

  manajemen: {
    pemesanan: '#navbar a#menu_manajemen_pemesanan',
    pesananPembelian: '#navbar a#menu_manajemen_pemesanan_v2',
    pembelian: '#navbar a#menu_manajemen_pembelian',
    penerimaanBarang: '#navbar a#menu_manajemen_pembelian_v2',
    pembayaranFaktur: '#navbar a#menu_manajemen_pembayaran_faktur',
    returObat: '#navbar a#menu_manajemen_retur',
    distribusiObat: '#navbar a#menu_manajemen_distribusi_obat',
    pengaturanMarginPenjamin: '#navbar a#menu_manajemen_harga_obat',
    stokObat: '#navbar a#menu_manajemen_stok_obat',
    stokOpname: '#navbar a#menu_manajemen_stok_opname',
    pembelianOnline: '#navbar a#menu_manajemen_pbf_online',
    pegawai: '#navbar a#menu_kepegawaian_pegawai',
    pengguna: '#navbar a#menu_kepegawaian_pengguna',
    jadwalPelayananDanDokter: '#navbar a#menu_kepegawaian_jadwal_pelayanan_dan_dokter',
    jadwalShift: '#navbar a#menu_kepegawaian_jadwal_shift',
    broadcast: '#navbar a#menu_broadcast',
  },

  backOffice: {
    transaksi: '#navbar a#menu_master_transaksikeu',
    jurnal: '#navbar a#menu_master_jurnal',
    penyusutanAset: '#navbar a#menu_master_penyusutanaset',
    bukuBesar: '#navbar a#menu_master_bukubesar',
    neracaSaldo: '#navbar a#menu_master_neracasaldo',
  },

  masterData: {
    coa: '#navbar a#menu_master_coa',
    transaksi: '#navbar a#menu_master_transaksi',
    aset: '#navbar a#menu_master_aset',
    asetTetap: '#navbar a#menu_master_masettetap',
    pembayaran: '#navbar a#menu_master_mpembayaran',
    mappingAplikasi: '#navbar a#menu_master_konfigurasi',
    obat: '#navbar a#menu_master_obat_v2',
    dataTindakan: '#navbar a#menu_master_tindakan',
    dataTindakanV3: '#navbar a#menu_master_tindakan[href*="/master/tindakan/v3"]',
    paketLaboratorium: '#navbar a#menu_master_paket_laboratorium',
    laboratorium: '#navbar a#menu_master_laboratorium',
    radiologi: '#navbar a#menu_master_radiologi',
    radiologiV3: '#navbar a#menu_master_radiologi[href*="/mradiologi/v3"]',
    penjamin: '#navbar a#menu_master_penjamin',
    penjaminV3: '#navbar a#menu_master_penjamin_v3',
    pbf: '#navbar a#menu_master_pbf',
    pbfV3: '#navbar a#menu_master_pbf[href*="/mpbf/v3"]',
    komponenTarif: '#navbar a#menu_master_mkomponentarif',
    komponenTarifV3: '#navbar a#menu_master_mkomponentarif_v3',
    metodePembayaran: '#navbar a#menu_master_metode_pembayaran',
    voucher: '#navbar a#menu_master_voucher',
    diagnosa: '#navbar a#menu_master_diagnosa',
    diagnosaV3: '#navbar a#menu_master_diagnosa_v3',
    retur: '#navbar a#menu_master_retur',
    paketLayanan: '#navbar a#menu_master_paket_layanan_v2',
    katalogPertanyaanMcu: '#navbar a#menu_master_pertanyaan_mcu',
    klinik: '#navbar a#menu_master_klinik',
    ruangan: '#navbar a#menu_master_mruangan',
    ruanganV3: '#navbar a#menu_master_mruangan[href*="/mruangan/v3"]',
    kamarBed: '#navbar a#menu_master_kamar',
    libur: '#navbar a#menu_master_libur',
    ruanganAkses: '#navbar a#menu_master_mruanganakses',
    ruanganAksesV3: '#navbar a#menu_master_mruanganakses_v3',
    perlengkapan: '#navbar a#menu_master_perlengkapan',
    pembulatan: '#navbar a#menu_keuangan_pembulatan',
    wilayahKerja: '#navbar a#menu_wilayah_kerja',
    konfigurasiDashboardAntrean: '#navbar a#menu_config_antrian',
    konfigurasiForm: '#navbar a#menu_config_konfigurasiform',
    konfigurasiFormV3: '#navbar a#menu_config_konfigurasiform[href*="/konfigurasiform/v3"]',
    konfigurasiLayananKhusus: '#navbar a#menu_konfigurasi_layanankhusus',
    peranAkses: '#navbar a#menu_pengelolaan_peranakses',
    konfigurasiHargaObat: '#navbar a#menu_konfigurasi_resep',
    konfigurasiSediaanObat: '#navbar a#menu_konfigurasi_resep[href*="/konfigurasiobat"]',
    konfigurasiLaboratorium: '#navbar a#menu_config_konfigurasilaboratorium',
    templatePrint: '#navbar a#menu_config_custom_print',
    konfigurasiNomorSurat: '#navbar a#menu_config_konfigurasi_nomor_surat',
    signaturePegawai: '#navbar a#menu_signature_pegawai',
    signaturePegawaiV3: '#navbar a#menu_signature_pegawai[href*="/signaturepegawai/v3"]',
    pengaturanSignature: '#navbar a#menu_pengaturan_signature',
    pengaturanBpjs: '#navbar a#menu_master_pengaturan_bpjs',
    providerBpjs: '#navbar a#menu_master_bpjs_provider',
    poliFktlBpjs: '#navbar a#menu_master_bpjs_poli_fktl',
    dokterBpjs: '#navbar a#menu_master_bpjs_dokter',
    dokterBpjsV3: '#navbar a#menu_master_bpjs_dokter_v3',
    tindakanBpjs: '#navbar a#menu_master_bpjs_tindakan',
    laboratoriumBpjs: '#navbar a#menu_master_bpjs_laboratorium',
    obatBpjs: '#navbar a#menu_master_bpjs_obat',
    ruanganBpjs: '#navbar a#menu_master_bpjs_ruangan',
    ruanganBpjsV3: '#navbar a#menu_master_bpjs_ruangan[href*="/mruanganbpjs/v3"]',
    alergiBpjs: '#navbar a#menu_master_bpjs_alergi',
    sinkronBpjs: '#navbar a#menu_master_bpjs_sinkron',
    pengaturanBridgingBpjs: '#navbar a#menu_master_sinkron_bpjs',
    konfigurasiKlinisiaApps: '#navbar a#menu_data_api_rekam_medis',
    konfigurasiSatuSehat: '#navbar a#menu_data_api_rekam_medis[href$="/konfigurasisatusehat"]',
    konfigurasiSatuSehatV2:
      '#navbar a#menu_data_api_rekam_medis[href*="/konfigurasisatusehat/v2"]',
    setting: '#navbar a#menu_data_setting',
    konfigurasiVclaim: '#navbar a#menu_master_vclaim_konfigurasi',
    diagnosaProgramPrb: '#navbar a#menu_master_vclaim_diagnosa',
    spesialistik: '#navbar a#menu_master_konfigurasi[href*="/vclaim/spesialistik"]',
  },

  laporan: {
    kunjunganPasien: '#navbar a#menu_laporan_kunjungan_pasien',
    kunjunganPasienBpjs: '#navbar a#menu_laporan_kunjungan_pasien_bpjs',
    kunjunganLayanan: '#navbar a#menu_laporan_kunjungan_layanan',
    pelayananPasien: '#navbar a#menu_laporan_pelayanan_pasien',
    rekapitulasiKunjungan: '#navbar a#menu_laporan_rekapitulasi_kunjungan',
    pemeriksaanMedis: '#navbar a#menu_laporan_pemeriksaan_medis',
    pelayananResep: '#navbar a#menu_laporan_laporan_pelayanan_resep',
    pelayananLaboratorium: '#navbar a#menu_laporan_pelayanan_lab',
    pelayananRadiologi: '#navbar a#menu_laporan_pelayanan_radiologi',
    rujukanInternal: '#navbar a#menu_laporan_rujukan_internal',
    rujukanExternal: '#navbar a#menu_laporan_rujukan_external',
    tindakanDokterPerawat: '#navbar a#menu_laporan_laporan_tindakan_dokter',
    pemeriksaanLaboratorium: '#navbar a#menu_laporan_pemeriksaan_laboratorium',
    pemeriksaanRadiologi: '#navbar a#menu_laporan_pemeriksaan_radiologi',
    kinerjaKlinik: '#navbar a#menu_laporan_kinerja_klinik',
    pelayananRuangan: '#navbar a#menu_laporan_pelayanan_ruangan',
    penyakit: '#navbar a#menu_laporan_penyakit',
    tagihanAsuransi: '#navbar a#menu_laporan_tagihan_asuransi',
    obatKadaluarsa: '#navbar a#menu_laporan_obat_kadaluarsa',
    obatKadaluarsaV3: '#navbar a#menu_laporan_obat_kadaluarsa_v3',
    stokOpname: '#navbar a#menu_laporan_stok_opname',
    jasaTenagaMedis: '#navbar a#menu_laporan_jasa_tenaga_medis',
    surveyKuesioner: '#navbar a#menu_laporan_survey_kuesioner',
    kunjunganPtm: '#navbar a#menu_laporan_harian_kunjungan_ptm',
    kirimLaporan: '#navbar a#menu_kirim_laporan',
    laporan: '#navbar a#menu_laporan_all',
    sp3Lb1: '#navbar a#menu_laporan_sp3_lb1',
    sp3Lb2: '#navbar a#menu_laporan_sp3_lb2',
    kohort: '#navbar a#menu_laporan_kohort',
    kohortKia: '#navbar a#menu_laporan_kohort_kia',
    ptm: '#navbar a#menu_laporan_laporan_ptm',
    pendapatanHarian: '#navbar a#menu_laporan_pendapatan',
    pendapatanPendaftaran: '#navbar a#menu_laporan_pendapatan_pendaftaran',
    pendapatanTindakan: '#navbar a#menu_laporan_pendapatan_tindakan',
    pendapatanKasir: '#navbar a#menu_laporan_pendapatan_kasir',
    transaksiKasir: '#navbar a#menu_laporan_transaksi_kasir',
    pendapatanObat: '#navbar a#menu_laporan_pendapatan_obat',
    pendapatanAlkes: '#navbar a#menu_laporan_pendapatan_alkes',
    pendapatanLaboratorium: '#navbar a#menu_laporan_pendapatan_lab',
    pendapatanUtama: '#navbar a#menu_laporan_pendapatan_utama',
    dashboardFinance: '#navbar a#menu_dashboar_finance',
    dashboardKepatuhan: '#navbar a#menu_dashboard_kepatuhan',
    buatBaruLaporan: '#navbar a#menu_laporan_created[href*="/createdlaporan"]',
    desainerGrafik: '#navbar a#menu_desainer_grafik',
    monitoringSatuSehat: '#navbar a#menu_laporan_created[href*="/monitoring-satusehat"]',
  },

  grafik: {
    grafik: '#navbar a#menu_grafik[href$="/grafik"]',
    pasien: '#navbar a#menu_gis_pasien',
    penyakit: '#navbar a#menu_gis_penyakit',
    dashboard: '#navbar a#menu_grafik_dashboard',
    transaksiKeuangan: '#navbar a#menu_grafik_transaksikeuangan',
    neraca: '#navbar a#menu_grafik_neraca_keuangan',
    labaRugi: '#navbar a#menu_grafik_laba_rugi',
    perubahanModal: '#navbar a#menu_grafik_perubahan_modal',
    analisa: '#navbar a#menu_grafik_analisa_rasio',
  },

  user: {
    profil: '#navbar a#menu_user_profil',
    userGuide: '#navbar a#menu_user_userguide',
    update: '#navbar a#menu_user_update',
    umpanBalik: '#navbar a#menu_user_umpanbalik',
    keluar: '#navbar a#menu_user_logout',
  },
} as const;

export type NavbarMenu = keyof typeof NavbarLocator.menu;
